name:                pkg-a
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/githubuser/pkg-a#readme
license:             BSD-3-Clause
author:              Author name here
maintainer:          example@example.com
copyright:           2020 Author name here
category:            Web

verbatim:
  cabal-version: 3.0

dependencies:
  - base >= 4.7 && < 5

library:
  source-dirs:      src
  dependencies:
    - hedgehog

internal-libraries:
  pkg-a2:
    source-dirs: src2
    verbatim:
      visibility: public
    dependencies:
      - pkg-a
      - aeson

tests:
  pkg-a-test:
    source-dirs: test
    main: Main.hs
    dependencies:
      - pkg-a
      - pkg-a2
